### PR TITLE
Jekyll

### PR DESCRIPTION
**Pull request by Svenito**
Here's the PR for a Jekyll port. Let me know of any changes you would like or if you have any problems using it.

I've included a Rakefile so you can easily create new posts with `rake new_post` andentering the date of the talk in the `YYYY-MM-DD` format.
Also included are some recent talks, so you can see how the formatting behaves.

Cheers

### CODE REVIEW

**Comment by Jonty** [comment]
As promised last night:
* Can confirm that this is completely compatible with github pages Jekyll version and automatic builds
* Added a test post to check it updated and rebuilt correctly (by dropping a new file in _posts rather than using the Rakefile)
* Deployed it as a test thing on my own gh-pages domain so you can all look at it: http://jonty.github.io

Things that need to be done:
* Make the irc link in the footer either link to freenode webchat, or be an irc:// link (ideally both)
* I'll submit a PR that adds an automatic ical feed (though this isn't a blocker)
* A CNAME file needs to be added so dc4420.org can be CNAME'd to dc4420.github.io and served correctly

To switch to serving/building on github pages after this, the only things that need to happen are:
* This repository needs renaming from "website" to "dc4420.github.io"
* The dc4420.org domain needs A records for 192.30.252.154 and 192.30.252.153

**Comment by marksteward** [comment]
Thanks for the PR and sorry for not having time last week! Moving to Github hosting is a long-term thing, and requires us to ensure we're not breaking any pre-existing links/downloads first. I've put it at http://dc4420.org/new for now, and will invite comment.

**Comment by Svenito** [comment]
Sounds good to me. Tag me in any issues and I'll be happy to make changes.

**Comment by AdamLaurie** [comment]
On 17/07/15 14:05, Mark Steward wrote:
> Thanks for the PR and sorry for not having time last week! Moving to
> Github hosting is a long-term thing, and requires us to ensure we're not
> breaking any pre-existing links/downloads first. I've put it at
> http://dc4420.org/new for now, and will invite comment.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dc4420/website/pull/9#issuecomment-122268176>.
>

looks sexytastic to me!

nice work all! :)

cheers,
MM
-- 
Adam Laurie                         Tel: +44 (0) 20 7993 2690
Suite 7
61 Victoria Road
Surbiton
Surrey                              mailto:adam@algroup.co.uk
KT6 4JX                             http://rfidiot.org

**Comment by Jonty** [comment]
````_includes/header.html```` contains this:

````
<img src="http://dc4420.org/images/dc-skull-logo-yellow.png" width="60" height="60">
````

It should be changed to the following, so you don't get mixed-content warnings when serving the site over https:
````
6:    <img src="images/dc-skull-logo-yellow.png" width="60" height="60">
````

**Comment by marksteward** [comment]
Thanks for this Sven, I think it's significantly easier to manage this way.

**Pull request merged**
